feat:세일 생성 구현
samtuap/dongsanginong-client pull request #222
Opened 2024-10-21 14:39 UTC by cogns

## 📌 PR 타입

- [x] 기능 추가
- [ ] 기능 수정
- [ ] 리팩토링
- [ ] docs 작업
- [ ] 설정 변경

## 📄 작업 내용

세일 생성 구현

## 📷 결과 화면

패키지 생성 시 할인 설정 추가
![image](https://github.com/user-attachments/assets/a37ef924-404c-4fbe-a2b1-a0b6213c0ee8)

할인 설정 활성화
![image](https://github.com/user-attachments/assets/b50c0a74-171a-4626-a64f-a00e0a145aee)

할인 종료일 오류(다른 모달과 맞추기 위해서 어쩔수 없이 줄넘김을 포기했습니다...)
![image](https://github.com/user-attachments/assets/0e3fd8b6-1e38-4f97-8451-a422b275b32b)

할인 입력값 오류
![image](https://github.com/user-attachments/assets/4010bc5a-ad0d-4ab8-a7bf-d73bf42ca157)

## ✔️ 기타 사항

네이버 스토어에서는 상품을 등록할때 할인도 같이 등록해서 저도 비슷하게 만들어 봤습니다!
![image](https://github.com/user-attachments/assets/e1a06177-8b53-426a-b5bd-b326c6db4c8a)

## 🌳 작업 브랜치

closed #220

2024-10-21 23:50 UTC, H-Yeji commented
할인 선택란 아래 간격 맞춰주시고, 모달창은 글자가 많아지면 옆으로 좀 늘리셔도 됩니다 : ) 그렇게 맞춰주시면 감사하겠습니다. 아니면, 종료일은 시작일 이후여야 합니다. 이런 멘트로 바꿔주세요 !

2024-10-23 06:21 UTC, clean2001 requested changes
패키지를 등록/수정할 때 할인을 정하는 게 아닌, 할인을 설정하고 그걸 적용할 패키지를 설정하는 방식으로 수정해주실 수 있으신가요??

2024-10-23 13:13 UTC, cogns commented
> 패키지를 등록/수정할 때 할인을 정하는 게 아닌, 할인을 설정하고 그걸 적용할 패키지를 설정하는 방식으로 수정해주실 수 있으신가요??

근데 그러기엔 상품마다 순수익이 다 다르고, 할인을 했을 때 손익분기점도 다 다를텐데 할인을 먼저 설정하는것보다 각 상품마다 그에 맞는 할인을 넣는게 좋지 않을까요??

2024-10-24 00:37 UTC, tteia commented
> > 패키지를 등록/수정할 때 할인을 정하는 게 아닌, 할인을 설정하고 그걸 적용할 패키지를 설정하는 방식으로 수정해주실 수 있으신가요??
> 
> 근데 그러기엔 상품마다 순수익이 다 다르고, 할인을 했을 때 손익분기점도 다 다를텐데 할인을 먼저 설정하는것보다 각 상품마다 그에 맞는 할인을 넣는게 좋지 않을까요??

쿠폰처럼 상품에 할인을 적용하는 방식이면 전혀 상관없지 않을까요 ?
농부 본인이 손익분기점과 수익을 따졌을 때 손해인 것 같다면 해당 할인율을 적용하지 않으면 되고,
새로운 할인을 생성해서 적용하면 되는 문제 아닌가요 !? 쿠폰처럼 생각하시면 될 것 같아요...!!

2024-10-25 05:36 UTC, closed without merging